# File containing the input data. The columns are:
# * 'id': name of the object.
# * 'redshift': redshift of the object. If ≤0, the distance is assumed
# to be 10 pc. If NaN the photometric mode is enabled. In that case an
# explicit redshift grid must be provided in the redshfting module.
# * 'distance' (Mpc, optional): distance in Mpc. Optional, if present it
# will be used in lieu of the distance computed from the redshift
# assuming a Planck et al. (2018) cosmology.
# * band fluxes: fluxes in filters in mJy. Each column is identified
# with a unique filter name, for instance jwst.nircam.F200W for the 2 μm
# filter of the NIRCAM instrument onboard JWST. The known filters are
# avalaible from the command 'pcigale-filters list'.
# * line fluxes: fluxes in lines in W/m². Each column is identified
# after a unique line name prefixed with 'line.', for instance
# line.H-alpha. The known filters are available from the command
# 'pcigale-filters list'. It is possible to combine lines together, for
# instance line.NII-654.8+H-alpha+NII-658.3 will be the sum of Hα and
# the adjacent NII lines.
# * physical properties: values of the intensive and extensive physical
# properties (e.g., dust.luminosity for the dust luminosity). To
# determine the format of the columns and the units, it is suggested to
# do a minimal run and examine the output FITS table.
# * uncertainties: the uncertainties for the band and line fluxes as
# well as for the physical properties are given using the same column
# names with the '_err' suffix.
# Important notes:
# * Fluxes can be positive or negative.
# * Upper limits are indicated with a negative value for the
# uncertainty.
# * In case some fluxes are missing for some objects, they can be
# replaced with NaN.
# * This file is optional to generate the configuration file, in
# particular for the savefluxes module.
data_file = 

# Optional file containing the list of physical parameters. Each column
# must be in the form module_name.parameter_name, with each line being a
# different model. The columns must be in the order the modules will be
# called. The redshift column must be the last one. Finally, if this
# parameter is not empty, cigale will not interpret the configuration
# parameters given in pcigale.ini. They will be given only for
# information. Note that this module should only be used in conjonction
# with the savefluxes module. Using it with the pdf_analysis module will
# yield incorrect results.
parameters_file = 

# Available modules to compute the models. The order must be kept.
# SFH:
# * sfh2exp: double exponential.
# * sfhdelayed: delayed SFH with optional exponential burst.
# * sfhdelayedbq: delayed SFH with optional constant burst/quench.
# * sfhfromfile: arbitrary SFH read from an input file.
# * sfhperiodic: periodic SFH, exponential, rectangle or delayed.
# SSP:
# * bc03: Bruzual and Charlot 2003.
# * cb19: Charlot and Bruzual 2019.
# * bpassv2: BPASS 2.2
# * m2005: Maraston 2005.
# Nebular emission:
# * nebular: continuum and line nebular emission.
# Dust attenuation:
# * dustatt_modified_CF00: modified Charlot & Fall 2000 attenuation law.
# * dustatt_modified_starburst: modified Calzetti 2000 attenuaton law.
# Dust emission:
# * casey2012: Casey 2012 dust emission models.
# * dale2014: Dale et al. 2014 dust emission templates.
# * dl2007: Draine & Li 2007 dust emission models.
# * dl2014: Draine et al. 2014 update of the previous models.
# * themis: Themis dust emission models from Jones et al. (2017).
# AGN:
# * skirtor2016: AGN models from Stalevski et al. (2012, 2016).
# * fritz2006: AGN models from Fritz et al. (2006).
# X-ray:
# * yang20 (X-ray models from Yang et al. 2020).
# * lopez24 (X-ray models from Lopez et al. 2024).
# Radio:
# * radio: galaxy synchrotron emission and AGN; note:
# skirtor2016/fritz2006 is needed for AGN.
# Restframe parameters:
# * restframe_parameters: UV slope (β), IRX, D4000, equivalent width,
# etc.
# Redshift+IGM:
# * redshifting: mandatory, also includes the IGM from Meiksin (2006).
sed_modules = sfh2exp, bc03, redshifting

# Method used for statistical analysis. Available methods: pdf_analysis,
# savefluxes.
analysis_method = savefluxes

# Number of CPU cores to use in parallel.
cores = 22

# Bands and emission lines to consider. To take uncertainties into
# account, the name of the band or line must be indicated with the _err
# suffix as in the input flux file. For instance: galex.FUV,
# galex.FUV_err. The list of allowed bands and lines can be obtained
# with pcigale-filters list. Line names must be prefixed with 'line.',
# for instance line.H-alpha, as in the input flux file.
bands = jwst.miri.F1000W, jwst.miri.F1130W, jwst.nircam.F200W, jwst.miri.F2100W, hst.wfc3.uvis1.F275W, jwst.nircam.F300M, jwst.nircam.F335M, hst.wfc3.uvis1.F336W, jwst.nircam.F360M, hst.acs.wfc.F435W, hst.wfc3.uvis1.F438W, hst.acs.wfc.F555W, jwst.miri.F770W, hst.acs.wfc.F814W

# Properties to be considered. All properties are to be given in the
# rest frame rather than the observed frame. This is the case for
# instance the equivalent widths and for luminosity densities. The names
# correspond to those used in the input file with the uncertainties
# indicated with the _err suffix.
properties =

# Relative error added in quadrature to the uncertainties of the fluxes
# and the extensive properties. Uncertainties on intensive properties
# are left unchanged.
additionalerror = 0.1



# Configuration of the SED creation modules.
[sed_modules_params]

  [[sfh2exp]]
    # e-folding time of the main stellar population model in Myr.
    tau_main = 1e-10
    # e-folding time of the late starburst population model in Myr.
    tau_burst = 1e-10
    # Mass fraction of the late burst population.
    f_burst = 0
    # Age of the main stellar population in the galaxy in Myr. The precision
    # is 1 Myr.
    age = "eval np.unique(np.concatenate((np.arange(1, 11), np.int_(np.around(10**np.arange(1, 4.001, 0.01), 0)))))"
    # Age of the late burst in Myr. The precision is 1 Myr.
    burst_age = 1
    # Value of SFR at t = 0 in M_sun/yr.
    sfr_0 = 1.0
    # Normalise the SFH to produce one solar mass.
    normalise = True

  [[bc03]]
    # Initial mass function: 0 (Salpeter) or 1 (Chabrier).
    imf = 0
    # Metallicity of the stellar populations. Possible values are: 0.0001,
    # 0.0004, 0.004, 0.008, 0.02, 0.05.
    metallicity = 0.02
    # Age [Myr] of the separation between the young and the old star
    # populations. The default value in 10^7 years (10 Myr). Set to 0 not to
    # differentiate ages (only an old population).
    separation_age = 1

  [[redshifting]]
    # Redshift of the objects. Leave empty to use the redshifts from the
    # input file.
    redshift = 0


# Configuration of the statistical analysis method.
[analysis_params]
  # List of the physical properties to save. Leave empty to save all the
  # physical properties (not recommended when there are many models).
  variables = sfh.age, sfh.burst_age, sfh.f_burst, sfh.integrated, sfh.sfr, sfh.sfr100Myrs, sfh.sfr10Myrs, sfh.tau_burst, sfh.tau_main, stellar.age_m_star, stellar.beta0, stellar.imf, stellar.lum, stellar.lum_ly, stellar.lum_ly_old, stellar.lum_ly_young, stellar.lum_old, stellar.lum_young, stellar.m_gas, stellar.m_gas_old, stellar.m_gas_young, stellar.m_star, stellar.m_star_old, stellar.m_star_young, stellar.metallicity, stellar.n_ly, stellar.n_ly_old, stellar.n_ly_young, stellar.old_young_separation_age, universe.age, universe.luminosity_distance, universe.redshift
  # If True, save the generated spectrum for each model.
  save_sed = True
  # Number of blocks to compute the models. Having a number of blocks
  # larger than 1 can be useful when computing a very large number of
  # models or to split the result file into smaller files.
  blocks = 1
